name: elsheikh_customs_app
description: "تطبيق أعمال الشيخ مختار للتخليص الجمركي - إدارة العملاء، قراءة الفواتير وتوليد الـ PDF"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.1.0
  pdf: ^3.10.8
  printing: ^5.13.1
  path_provider: ^2.1.2
  path: ^1.9.0
  image_picker: ^1.0.7
  intl: ^0.20.2
  uuid: ^4.3.3
  google_mlkit_text_recognition: ^0.15.1
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
